# Generated by Django 5.2.17 on 2026-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
